apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: deploy-1
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      zone: ss
  template: 
    metadata: 
      name: my-pod 
      labels: 
        zone: ss
    spec: 
      containers: 
      - name: ctn 
        image: nginx 
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata: 
  name: sss
spec: 
  ports:
  - name: sss-port 
    targetPort: 80 
    port: 80 
  selector:
    zone: ss
  type: LoadBalancer
